"""
ForeWatt Dashboard - Anomaly Monitor (IsolationForest)
Unified anomaly detection page for consumption and price.
"""
import streamlit as st
import pandas as pd
from pathlib import Path
import plotly.graph_objects as go
import sys

# Add parent utils to path
sys.path.insert(0, str(Path(__file__).parent.parent))

from utils import PAGE_CONFIG, PROFESSIONAL_CSS, HIDE_OPTIMIZATION_NAV_CSS, get_model_colors, render_page_header

# Page configuration
st.set_page_config(**PAGE_CONFIG)

# Apply professional styling
st.markdown(PROFESSIONAL_CSS, unsafe_allow_html=True)

# Check session state for model selection
if 'selected_model' not in st.session_state or st.session_state.selected_model is None:
    st.warning("Please select a model type first.")
    if st.button("Go to Home", use_container_width=True):
        st.switch_page("Home.py")
    st.stop()

# Get model type from session state
MODEL_TYPE = st.session_state.selected_model

# Hide Optimization Architecture from sidebar for consumption mode
if MODEL_TYPE == 'consumption':
    st.markdown(HIDE_OPTIMIZATION_NAV_CSS, unsafe_allow_html=True)

# Configure based on model type
colors = get_model_colors(MODEL_TYPE)
if MODEL_TYPE == 'consumption':
    ICON = "🚨"
    TITLE = "Consumption Anomaly Monitor"
    COLOR = colors['primary']
    UNIT = "MWh"
    TARGET_LABEL = "Consumption"
    TARGET_COL = "consumption"
    CSV_NAME = "anomaly_results.csv"
else:
    ICON = "🚨"
    TITLE = "Price Anomaly Monitor"
    COLOR = colors['primary']
    UNIT = "TL/MWh"
    TARGET_LABEL = "Price"
    TARGET_COL = "price_real"
    CSV_NAME = "anomaly_results_price.csv"

# Header with back button
col1, col2 = st.columns([6, 1])
with col1:
    render_page_header(ICON, TITLE, "Monitor anomalies and forecast deviations", COLOR)
with col2:
    if st.button("← Back", key="back_menu_anomaly", use_container_width=True):
        st.switch_page("Home.py")

st.markdown(f"""
<div class="info-box">
    Source: <code>reports/{CSV_NAME}</code> (generated by anomaly detection script)
</div>
""", unsafe_allow_html=True)

# CSV path
CSV_PATH = Path(__file__).resolve().parents[2] / "reports" / CSV_NAME

# Also try the default path if model-specific doesn't exist
if not CSV_PATH.exists():
    CSV_PATH = Path(__file__).resolve().parents[2] / "reports" / "anomaly_results.csv"

PLOTLY_CONFIG = {
    "scrollZoom": True,
    "displaylogo": False,
    "modeBarButtonsToRemove": ["lasso2d", "select2d"],
}


@st.cache_data
def load_anomaly_csv(path: Path) -> pd.DataFrame:
    df = pd.read_csv(path)
    df["timestamp"] = pd.to_datetime(df["timestamp"], utc=True).dt.tz_convert("Europe/Istanbul")
    df = df.sort_values("timestamp").reset_index(drop=True)
    return df


if not CSV_PATH.exists():
    st.error(f"CSV not found: {CSV_PATH}")
    st.info("Run the anomaly detection script first: `python scripts/runAnomalyLocal.py`")
    st.stop()

df = load_anomaly_csv(CSV_PATH)

# Determine actual column names
if TARGET_COL not in df.columns and 'consumption' in df.columns:
    TARGET_COL = 'consumption'
FORECAST_COL = f"{TARGET_COL}_forecast" if f"{TARGET_COL}_forecast" in df.columns else "consumption_forecast"

# Sidebar controls
with st.sidebar:
    st.header("Filters")

    min_ts = df["timestamp"].min()
    max_ts = df["timestamp"].max()

    default_start = (max_ts - pd.Timedelta(days=90)).date()
    default_end = max_ts.date()

    date_range = st.date_input(
        "Date range",
        value=(default_start, default_end),
        min_value=min_ts.date(),
        max_value=max_ts.date(),
    )

    tz = df["timestamp"].dt.tz

    if isinstance(date_range, tuple) and len(date_range) == 2:
        start_date = pd.Timestamp(date_range[0]).tz_localize(tz)
        end_date = (pd.Timestamp(date_range[1]) + pd.Timedelta(days=1) - pd.Timedelta(seconds=1)).tz_localize(tz)
    else:
        start_date = pd.Timestamp(min_ts.date()).tz_localize(tz)
        end_date = (pd.Timestamp(max_ts.date()) + pd.Timedelta(days=1) - pd.Timedelta(seconds=1)).tz_localize(tz)

    show_anoms = st.checkbox("Show anomalies (red markers)", value=True)

    score_min = float(df["anomaly_score"].min())
    score_max = float(df["anomaly_score"].max())
    score_thr = st.slider("Min anomaly_score (for markers)", score_min, score_max, score_min)

    top_k = st.slider("Top K table", 10, 200, 50)

    st.divider()
    st.caption("Zoom tips:")
    st.caption("- Mouse wheel: zoom")
    st.caption("- Drag: pan")
    st.caption("- Double click: reset")

# Window data
d = df[(df["timestamp"] >= start_date) & (df["timestamp"] <= end_date)].copy()

# Anomaly markers
anom = d[(d["is_anomaly"] == 1) & (d["anomaly_score"] >= score_thr)].copy()

# KPI row
c1, c2, c3, c4, c5, c6 = st.columns(6)
c1.metric("Rows (window)", f"{len(d):,}")
c2.metric("Anomalies (markers)", f"{len(anom):,}")
c3.metric("Anomaly rate", f"{(len(anom)/len(d)*100 if len(d) else 0):.2f}%")
c4.metric("Max score (window)", f"{(anom['anomaly_score'].max() if len(anom) else 0):.4f}")
c5.metric("Max |residual|", f"{(d['residual'].abs().max() if len(d) else 0):.0f}")
c6.metric("Mean |residual|", f"{(d['residual'].abs().mean() if len(d) else 0):.0f}")

st.divider()

left, right = st.columns([2.2, 1], gap="large")

with left:
    st.subheader(f"Actual vs Forecast (with anomaly markers)")

    fig = go.Figure()
    fig.add_trace(go.Scatter(
        x=d["timestamp"], y=d[TARGET_COL],
        mode="lines", name=TARGET_LABEL,
        line=dict(color=COLOR)
    ))
    fig.add_trace(go.Scatter(
        x=d["timestamp"], y=d[FORECAST_COL],
        mode="lines", name="Forecast",
        line=dict(color='#1f77b4')
    ))

    if show_anoms and len(anom):
        fig.add_trace(go.Scatter(
            x=anom["timestamp"], y=anom[TARGET_COL],
            mode="markers",
            name=f"Anomaly ({len(anom)})",
            marker=dict(size=9, color="red", symbol="circle"),
        ))

    fig.update_layout(
        height=540,
        margin=dict(l=10, r=10, t=40, b=10),
        legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="right", x=1),
        dragmode="pan",
        hovermode="x unified",
    )
    fig.update_xaxes(rangeslider_visible=True)
    st.plotly_chart(fig, use_container_width=True, config=PLOTLY_CONFIG)

    st.subheader("Anomalies Table (in window)")
    if len(anom):
        show_cols = ["timestamp", TARGET_COL, FORECAST_COL, "residual", "anomaly_score"]
        available_cols = [c for c in show_cols if c in anom.columns]
        st.dataframe(
            anom.sort_values("anomaly_score", ascending=False)[available_cols].head(top_k),
            use_container_width=True,
            hide_index=True,
        )
    else:
        st.info("No anomalies in this window. Try lowering the min anomaly_score or expanding the date range.")

with right:
    st.subheader("Residual (Actual - Forecast)")

    fig2 = go.Figure()
    fig2.add_trace(go.Scatter(
        x=d["timestamp"], y=d["residual"],
        mode="lines", name="Residual",
        line=dict(color=COLOR)
    ))
    fig2.add_hline(y=0)

    if show_anoms and len(anom):
        fig2.add_trace(go.Scatter(
            x=anom["timestamp"], y=anom["residual"],
            mode="markers",
            name=f"Anomaly ({len(anom)})",
            marker=dict(size=9, color="red", symbol="circle"),
        ))

    fig2.update_layout(
        height=380,
        margin=dict(l=10, r=10, t=40, b=10),
        legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="right", x=1),
        dragmode="pan",
        hovermode="x unified",
    )
    st.plotly_chart(fig2, use_container_width=True, config=PLOTLY_CONFIG)

    st.subheader("Score Summary (window)")
    if len(d):
        st.write(d["anomaly_score"].describe())
    else:
        st.info("No data in selected range.")

    st.divider()

    st.subheader("Anomaly Distribution")
    if len(d) and 'is_anomaly' in d.columns:
        anom_counts = d['is_anomaly'].value_counts()
        fig3 = go.Figure(data=[go.Pie(
            labels=['Normal', 'Anomaly'],
            values=[anom_counts.get(0, 0), anom_counts.get(1, 0)],
            marker_colors=['#2ca02c', '#d62728'],
            hole=0.4
        )])
        fig3.update_layout(height=250, margin=dict(l=10, r=10, t=10, b=10))
        st.plotly_chart(fig3, use_container_width=True, config=PLOTLY_CONFIG)
