import streamlit as st
import pandas as pd
from pathlib import Path
import plotly.graph_objects as go

st.set_page_config(page_title="Anomaly Monitor", layout="wide")

st.title("🚨 Anomaly Monitor (IsolationForest)")
st.caption("Source: reports/anomaly_results.csv (generated by scripts/runAnomalyLocal.py)")

CSV_PATH = Path(__file__).resolve().parents[2] / "reports" / "anomaly_results.csv"

PLOTLY_CONFIG = {
    "scrollZoom": True,   # mouse wheel zoom
    "displaylogo": False,
    "modeBarButtonsToRemove": ["lasso2d", "select2d"],
}

@st.cache_data
def load_anomaly_csv(path: Path) -> pd.DataFrame:
    df = pd.read_csv(path)
    # Normalize tz: parse as UTC then convert to Istanbul (prevents tz-aware vs naive compare errors)
    df["timestamp"] = pd.to_datetime(df["timestamp"], utc=True).dt.tz_convert("Europe/Istanbul")
    df = df.sort_values("timestamp").reset_index(drop=True)
    return df

if not CSV_PATH.exists():
    st.error(f"CSV not found: {CSV_PATH}")
    st.info("Önce anomaly runner çalıştır:  python scripts\\runAnomalyLocal.py")
    st.stop()

df = load_anomaly_csv(CSV_PATH)

# --- Sidebar controls ---
with st.sidebar:
    st.header("Filters")

    min_ts = df["timestamp"].min()
    max_ts = df["timestamp"].max()

    default_start = (max_ts - pd.Timedelta(days=90)).date()
    default_end = max_ts.date()

    date_range = st.date_input(
        "Date range",
        value=(default_start, default_end),
        min_value=min_ts.date(),
        max_value=max_ts.date(),
    )

    tz = df["timestamp"].dt.tz

    if isinstance(date_range, tuple) and len(date_range) == 2:
        start_date = pd.Timestamp(date_range[0]).tz_localize(tz)
        end_date = (pd.Timestamp(date_range[1]) + pd.Timedelta(days=1) - pd.Timedelta(seconds=1)).tz_localize(tz)
    else:
        start_date = pd.Timestamp(min_ts.date()).tz_localize(tz)
        end_date = (pd.Timestamp(max_ts.date()) + pd.Timedelta(days=1) - pd.Timedelta(seconds=1)).tz_localize(tz)

    show_anoms = st.checkbox("Show anomalies (red markers)", value=True)

    # This threshold filters ONLY anomaly markers (lines always show full window)
    score_min = float(df["anomaly_score"].min())
    score_max = float(df["anomaly_score"].max())
    score_thr = st.slider("Min anomaly_score (for markers)", score_min, score_max, score_min)

    top_k = st.slider("Top K table", 10, 200, 50)

    st.divider()
    st.caption("Zoom tips:")
    st.caption("• Mouse wheel: zoom")
    st.caption("• Drag: pan (move)")
    st.caption("• Double click: reset")
    st.caption("• Modebar’dan Zoom seçersen drag ile zoom da yaparsın")

# --- Window data (lines) ---
d = df[(df["timestamp"] >= start_date) & (df["timestamp"] <= end_date)].copy()

# --- Anomaly markers (filtered by score) ---
anom = d[(d["is_anomaly"] == 1) & (d["anomaly_score"] >= score_thr)].copy()

# --- KPI row ---
c1, c2, c3, c4, c5, c6 = st.columns(6)
c1.metric("Rows (window)", f"{len(d):,}")
c2.metric("Anomalies (markers)", f"{len(anom):,}")
c3.metric("Anomaly rate", f"{(len(anom)/len(d)*100 if len(d) else 0):.2f}%")
c4.metric("Max score (window)", f"{(anom['anomaly_score'].max() if len(anom) else 0):.4f}")
c5.metric("Max |residual|", f"{(d['residual'].abs().max() if len(d) else 0):.0f}")
c6.metric("Mean |residual|", f"{(d['residual'].abs().mean() if len(d) else 0):.0f}")

st.divider()

left, right = st.columns([2.2, 1], gap="large")

with left:
    st.subheader("📈 Actual vs Forecast (with anomaly markers)")

    fig = go.Figure()
    fig.add_trace(go.Scatter(
        x=d["timestamp"], y=d["consumption"],
        mode="lines", name="consumption"
    ))
    fig.add_trace(go.Scatter(
        x=d["timestamp"], y=d["consumption_forecast"],
        mode="lines", name="forecast"
    ))

    if show_anoms and len(anom):
        fig.add_trace(go.Scatter(
            x=anom["timestamp"], y=anom["consumption"],
            mode="markers",
            name=f"anomaly ({len(anom)})",
            marker=dict(size=9, color="red", symbol="circle"),
        ))

    fig.update_layout(
        height=540,
        margin=dict(l=10, r=10, t=40, b=10),
        legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="right", x=1),
        dragmode="pan",
        hovermode="x unified",
    )
    fig.update_xaxes(rangeslider_visible=True)  # easier navigation
    st.plotly_chart(fig, use_container_width=True, config=PLOTLY_CONFIG)

    st.subheader("🔴 Anomalies table (markers in window)")
    if len(anom):
        show_cols = ["timestamp", "consumption", "consumption_forecast", "residual", "anomaly_score"]
        st.dataframe(
            anom.sort_values("anomaly_score", ascending=False)[show_cols].head(top_k),
            use_container_width=True,
            hide_index=True,
        )
    else:
        st.info("Bu aralıkta marker yok. Min anomaly_score’u düşür veya date range’i genişlet.")
with right:
    st.subheader("📉 Residual (Actual - Forecast)")

    fig2 = go.Figure()
    fig2.add_trace(go.Scatter(
        x=d["timestamp"], y=d["residual"],
        mode="lines", name="residual"
    ))
    fig2.add_hline(y=0)

    if show_anoms and len(anom):
        fig2.add_trace(go.Scatter(
            x=anom["timestamp"], y=anom["residual"],
            mode="markers",
            name=f"anomaly residual ({len(anom)})",
            marker=dict(size=9, color="red", symbol="circle"),
        ))

    fig2.update_layout(
        height=380,
        margin=dict(l=10, r=10, t=40, b=10),
        legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="right", x=1),
        dragmode="pan",
        hovermode="x unified",
    )
    st.plotly_chart(fig2, use_container_width=True, config=PLOTLY_CONFIG)

    st.subheader("📊 Score summary (window)")
    if len(d):
        st.write(d["anomaly_score"].describe())
    else:
        st.info("Seçili aralık boş.")
