#!/bin/bash
# Show All Hyperparameter Configurations
# ======================================
# Displays summary of all available model configurations for grid search

echo "════════════════════════════════════════════════════════════════════════════════════════"
echo "                    FOREWATT HYPERPARAMETER CONFIGURATIONS                               "
echo "════════════════════════════════════════════════════════════════════════════════════════"
echo ""
echo "TARGETS:"
echo "  1. consumption  - Electricity demand (MWh)"
echo "  2. price_real   - Day-ahead market price (PTF, inflation-adjusted TL/MWh)"
echo ""
echo "════════════════════════════════════════════════════════════════════════════════════════"
echo ""

# Navigate to project root
cd "$(dirname "$0")/.." || exit 1

echo "📊 BASELINE MODELS (25 configurations)"
echo "────────────────────────────────────────────────────────────────────────────────────────"
python src/models/baseline/hyperparameter_configs.py
echo ""
echo ""

echo "🧠 DEEP LEARNING MODELS (21 configurations)"
echo "────────────────────────────────────────────────────────────────────────────────────────"
python src/models/deep_learning/hyperparameter_configs.py
echo ""
echo ""

echo "════════════════════════════════════════════════════════════════════════════════════════"
echo "                              QUICK START COMMANDS                                       "
echo "════════════════════════════════════════════════════════════════════════════════════════"
echo ""
echo "BASELINE MODELS:"
echo "  # Run all 25 baseline configs (both targets)"
echo "  python src/models/baseline/grid_search_runner.py"
echo ""
echo "  # Run specific models"
echo "  python src/models/baseline/grid_search_runner.py --models catboost xgboost"
echo ""
echo "  # Run for PTF price only"
echo "  python src/models/baseline/grid_search_runner.py --targets price_real"
echo ""
echo "  # Run for demand only"
echo "  python src/models/baseline/grid_search_runner.py --targets consumption"
echo ""
echo ""
echo "DEEP LEARNING MODELS:"
echo "  # Run all 21 deep learning configs (both targets)"
echo "  python src/models/deep_learning/grid_search_runner.py"
echo ""
echo "  # Run specific models"
echo "  python src/models/deep_learning/grid_search_runner.py --models nhits tft"
echo ""
echo "  # Run with Optuna optimization (best results)"
echo "  python src/models/deep_learning/grid_search_runner.py --use-optuna --n-trials 50"
echo ""
echo ""
echo "════════════════════════════════════════════════════════════════════════════════════════"
echo "                              EXPECTED RUNTIME                                           "
echo "════════════════════════════════════════════════════════════════════════════════════════"
echo ""
echo "BASELINE (CPU):"
echo "  • Light configs only:     ~1 hour"
echo "  • All 25 configs:         ~3-5 hours"
echo ""
echo "DEEP LEARNING (GPU recommended):"
echo "  • Light configs:          ~30-60 minutes"
echo "  • All 21 configs:         ~3-8 hours"
echo "  • With Optuna (50 trials): ~10-24 hours"
echo ""
echo "DEEP LEARNING (CPU - not recommended):"
echo "  • Light configs:          ~2-4 hours"
echo "  • All configs:            ~12-24 hours"
echo ""
echo ""
echo "════════════════════════════════════════════════════════════════════════════════════════"
echo "For more details, see: docs/HYPERPARAMETER_GRID_SEARCH.md"
echo "════════════════════════════════════════════════════════════════════════════════════════"
